packages:
  - apps/*
  - packages/*
allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
  extract-file-icon: true
  get-windows: true
  node-window-manager: true
  uiohook-napi: true
